### PR TITLE
Add @SendPaperdoll, add Decay ITEM never sleep

### PR DESCRIPTION
**Pull request by Jhobean**

### CODE REVIEW

**Comment by cbnolok** [comment]
Could you add more details in the changelog about when the paperdoll is requested?

**Comment by Jhobean** [comment]
I reworked the sector sleep function to avoid ALL attr_decay ITEM to never sleep. This will avoid to have useless item stuck at TIMER=0 on sleeping sector.

This change will fix this issue too : #467

**Comment by Jhobean** [comment]
@cbnolok Would you like to take some time to check this and/or comment plz.

**Comment by cbnolok** [comment]
I'd use the cansleep method to check for the decay flag

**Comment by Jhobean** [comment]
OK @cbnolok I made it. i was looking cansleep method but it exist only for sector. For item it's cantick. So I just considere attr_decay on the same way of item with flag CAN_No_Sleep.

**Pull request merged**
