### PR TITLE
Port from 56d: missing buff icons

### PR DESCRIPTION
**Pull request by DavideRei**
Added to enum BUFF_ICONS missing icons from 56d.

### CODE REVIEW

**Comment by AtillaG1** [comment]
It seems like there should be much more, but they are mixed inside the other ones feels like.
https://pastebin.com/dZYeLf6k

**Comment by DavideRei** [comment]
> It seems like there should be much more, but they are mixed inside the other ones feels like. https://pastebin.com/dZYeLf6k

I added all the missing ones from 56d

image

**Comment by Jhobean** [comment]
That seem correct

**Comment by DavideRei** [comment]
It seems to work. It depends also on client version

image

ClassicUO doesn't show all icons
image

**Pull request merged**
