### PR TITLE
Fix: Spawn Timer -1 was not working if trigger was not use.

### PR DESCRIPTION
**Pull request by Jhobean**

### CODE REVIEW

**Comment by AtillaG1** [comment]
Its working now, just one small thing.
Once the timer is -1 and spawn is full, and for any reason, you change it timer to 1, then it will never fall to -1 again, until the whole process is repeated. (spawned last NPC and once the spawn is full, it will go -1 again).

**Comment by Jhobean** [comment]
Yes the verification is make when char is add  and not when timer reach 0. If we want add the verificatino on timer 0 it requiere a big rework. Personnaly I dont want to go there.

**Comment by AtillaG1** [comment]
> Yes the verification is make when char is add and not when timer reach 0. If we want add the verificatino on timer 0 it requiere a big rework. Personnaly I dont want to go there.

yes, i personally think there is no way you could anyhow set the timer to anything after its -1. I just found out because all my spawns needs to be re-created to work as it should, but with worldspawner its easy, and even if its for someone with full shard, it would get fix overtime once people clear the spawned monsters.

I think Nolok mentioned on DC that it should be fixed just to be sure, but if its a lot of work, i dont think its critical problem in any way.

**Comment by Jhobean** [comment]
You can force a respawn global of you spawn.
https://github.com/Sphereserver/Scripts-X/blob/15685aee014f7a16c206d0287e4f8f2e1d9f356c/functions/f_gm_utilities.scp#L34

**Comment by AtillaG1** [comment]
👀

**Comment by Jhobean** [comment]
Nolok said he will check this weekend

**Comment by Jhobean** [comment]
> 👀

aDD THIS TO YOUR SCRIPT IT WILL WORK 
on=@DelObj //Called when a object is remove from the list of type t_spawn
//src / i / ARGO -> the uid of the spawn
//ARGN (R/W) -> Time in second for next spawn.

```
on=@AddObj //Called when a object is added to the list of type t_spawn
//src / i -> the uid of the spawn
//ARGO -> the uid of char/item add
//ARGN (R/W) -> Time in second for next spawn. Server will set to -1 if spawn is 

[typedef t_spawn_item]
on=@DelObj //Called when a object is remove from the list of type t_spawn
//src / i / ARGO -> the uid of the spawn
//ARGN (R/W) -> Time in second for next spawn.

on=@AddObj //Called when a object is added to the list of type t_spawn
//src / i -> the uid of the spawn
//ARGO -> the uid of char/item add
//ARGN (R/W) -> Time in second for next spawn. Server will set to -1 if spawn is 
```

I just founnd a bug if you reset a spawn with 1 NPC, it will not launch addobj and set to -1

**Comment by Jhobean** [comment]
Ready Work like a Charm!

**Comment by AtillaG1** [comment]
> > 👀
> 
> aDD THIS TO YOUR SCRIPT IT WILL WORK
> 
> ```
> [typedef t_spawn_char]
> on=@DelObj //Called when a object is remove from the list of type t_spawn
> //src / i / ARGO -> the uid of the spawn
> //ARGN (R/W) -> Time in second for next spawn.
> 
> on=@AddObj //Called when a object is added to the list of type t_spawn
> //src / i -> the uid of the spawn
> //ARGO -> the uid of char/item add
> //ARGN (R/W) -> Time in second for next spawn. Server will set to -1 if spawn is 
> 
> [typedef t_spawn_item]
> on=@DelObj //Called when a object is remove from the list of type t_spawn
> //src / i / ARGO -> the uid of the spawn
> //ARGN (R/W) -> Time in second for next spawn.
> 
> on=@AddObj //Called when a object is added to the list of type t_spawn
> //src / i -> the uid of the spawn
> //ARGO -> the uid of char/item add
> //ARGN (R/W) -> Time in second for next spawn. Server will set to -1 if spawn is 
> ```
> 
> I just founnd a bug if you reset a spawn with 1 NPC, it will not launch addobj and set to -1

added it to scripts and it does set to -1 🤩

**Comment by Jhobean** [comment]
> > > 👀
> > 
> > 
> > aDD THIS TO YOUR SCRIPT IT WILL WORK
> > ```
> > [typedef t_spawn_char]
> > on=@DelObj //Called when a object is remove from the list of type t_spawn
> > //src / i / ARGO -> the uid of the spawn
> > //ARGN (R/W) -> Time in second for next spawn.
> > 
> > on=@AddObj //Called when a object is added to the list of type t_spawn
> > //src / i -> the uid of the spawn
> > //ARGO -> the uid of char/item add
> > //ARGN (R/W) -> Time in second for next spawn. Server will set to -1 if spawn is 
> > 
> > [typedef t_spawn_item]
> > on=@DelObj //Called when a object is remove from the list of type t_spawn
> > //src / i / ARGO -> the uid of the spawn
> > //ARGN (R/W) -> Time in second for next spawn.
> > 
> > on=@AddObj //Called when a object is added to the list of type t_spawn
> > //src / i -> the uid of the spawn
> > //ARGO -> the uid of char/item add
> > //ARGN (R/W) -> Time in second for next spawn. Server will set to -1 if spawn is 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I just founnd a bug if you reset a spawn with 1 NPC, it will not launch addobj and set to -1
> 
> added it to scripts and after spawning last npc it does set to -1 🤩
Be aware, old .exe do not set to -1 the spawn with 1 char.

After this merge, it will work and you dont need to add trigger in script anymore

**Pull request merged**
