### PR TITLE
t_multi_addon redeed fix

### PR DESCRIPTION
**Pull request by GladieUO**
Issue #1313
The code was expecting the pOwner to be defined, but since the multi with t_multi_addon are mostly used for the house decoration, placed by players independently from deeds, we also need to check for the player doing the redeeding, since there is no owner on this multi.

The lack of owner would cause the code to be returned 

as always, any revision of my fix is appreciated, as it might not be perfect.

### CODE REVIEW

**Comment by cbnolok** [comment]
Could you add a changelog entry, and change uidChar to a name more meaningful, like uidReededingChar?

**Comment by GladieUO** [comment]
> Could you add a changelog entry, and change uidChar to a name more meaningful, like uidReededingChar?

should be good to go. Dont know why is changelog in conflict, I added all the old entries.

**Comment by GladieUO** [comment]
> > Could you add a changelog entry, and change uidChar to a name more meaningful, like uidReededingChar?
> 
> should be good to go. Dont know why is changelog in conflict, I added all the old entries.

Ok not yet, something is wrong 😁

**Comment by cbnolok** [comment]
Something changed in the build system, i'll try to fix that

**Pull request merged**
