### PR TITLE
CAN_I_DAMAGEABLE not updating status bar

### PR DESCRIPTION
**Pull request by GladieUO**
Another attempt for the small fix. #1248 also together with this we should consider #1260
The status bar would not get updated when you lower hits on the item with the flag.

**Only way it would get updated is:**
1. reopening status
2. changing some value on item (like MORE1 ++)
3. Targeting item by whatever

### CODE REVIEW

**Comment by Tolokio** [comment]
does that fix works?

**Comment by AtillaG1** [comment]
> does that fix works?

does for me. Everytime the hits gets changed from the custom script, statusbar updated. Before it didnt. If its correct fix im not sure.

**Comment by Tolokio** [comment]
Confirmed bug and confirmed that Gladie's fix works. But you lack the fix as well for maxhits
image

I dont know if it is how it should  be fixed but works.

Anyway, I found something weird. maybe is normal I dont know.

image
image

**Comment by AtillaG1** [comment]
I wasnt sure if we need to have it update on maxhits. Maybe if there is like 50/100 hits and you decrease maxhits to 75 so the ratio of status would change too?

**Comment by Tolokio** [comment]
> I wasnt sure if we need to have it update on maxhits. Maybe if there is like 50/100 hits and you decrease maxhits to 75 so the ratio of status would change too? I will update the PR.

You should split commits because there is a fix for follower slots.

Well, I think maxhits is set after the item is created or maybe placed in the world so..., and custom scripts could need it too. For example, a repair system that reduces maxhits but sets hits to 100%.

Anyway, I'm not sure if that's the correct approach or if it's necessary. I think u can force the ticks just giving a timer to the item. let me check

**Comment by AtillaG1** [comment]
> > I wasnt sure if we need to have it update on maxhits. Maybe if there is like 50/100 hits and you decrease maxhits to 75 so the ratio of status would change too? I will update the PR.
> 
> You should split commits because there is a fix for follower slots.
> 
 I Made new branch for this fix but somehow it shows also the followerslots I dunno why 🤐

**Comment by Tolokio** [comment]
U need to do a branch from source-x instead from ur own fork.
image

Then do the changes on that branch and pull. Remember u need to edit changelog as well.

**Comment by cbnolok** [comment]
Did you manage to remove the FOLLOWERSLOTS change from this PR?

**Comment by AtillaG1** [comment]
> Did you manage to remove the FOLLOWERSLOTS change from this PR?

I think I managed to do it right now.

**Comment by cbnolok** [comment]
I'm sorry, could you fix the conflicts please?

**Comment by GladieUO** [comment]
> I'm sorry, could you fix the conflicts please?

should be done

**Comment by cbnolok** [comment]
Manually merged.

**Pull request closed without merging**
