### PR TITLE
Fix for GM don't see same PLEVEL GM hidden (issue #506 )

### PR DESCRIPTION
**Pull request by Jhobean**
Like explained in issue #506 2 GM with same Plevel are not able to see each other when they are invisible.

On the script, the result of comparaison of plevel need to have a "0" to be able to see the target. The comparaison <= was not appropriate because same Plevel give a "1".

### CODE REVIEW

**Comment by Nirad** [comment]
👍

**Comment by cbnolok** [comment]
I'd like to add that as an optional feature, like a new ini setting: CanSeeSamePLevel. I'm open to other ideas though!

**Comment by GitMadKing** [comment]
agree. not as default. but optional YES


---- Attivato dom, 18 ott 2020 19:04:02 +0200 cbnolok <notifications@github.com> ha scritto ----




I'd like to add that as an optional feature, like a new ini setting: CanSeeSamePLevel. I'm open to other ideas though!

**Comment by Jhobean** [comment]
Ini setting like this?
//Gm with same level can see each other = 0
// Gm with same plevel dont see each other = -1
// All plevel over x see all gm = x (2 to 7)
CanSeeSamePLevel=0

**Comment by Jhobean** [comment]
I dont really understand the purpose of this, only wish to fix the actual bug:smile:

**Comment by FiLoUs64** [comment]
> I dont really understand the purpose of this, only wish to fix the actual bug😄

They said it's not a bug... was like this in 55i I think, you can't see same plevel

**Comment by cbnolok** [comment]
Yes like that, simply because they changed the default behavior since 56, it's not a bug

**Comment by GitMadKing** [comment]
add a (55 like) with -1does sphere has a default value for unset ini settings?i mean, if after this update, i change the "exe" but not the sphere.ini is a default in core to some value and then "updated" by sphere.ini settings or what?Marius ---- On mer, 21 ott 2020 06:54:45 +0200  notifications@github.com  wrote ----
Yes like that, simply because they changed the default behavior since 56, it's not a bug

**Comment by Jhobean** [comment]
Replace By this one https://github.com/Sphereserver/Source-X/pull/522

**Pull request closed without merging**
