### PR TITLE
New trigger @HitReactive and Override tag

### PR DESCRIPTION
**Pull request by canerksk**
OVERRIDE.AMMONOREQUIRED  = If a weapon has this tag, it will not ask for an arrow when shooting.

More customizable reactive armor spell damage returns

### CODE REVIEW

**Comment by cbnolok** [comment]
It looks like this branch is up to date with the branch of your other pull requests. They should both originate from the last dev branch; if i pull this, i will pull also the changes you did in the other pr.
Anyways, isn't your TAG redundant with t_weapon_bow/xbow TDATA3 and @Hit trigger's LOCAL.ARROWHANDLED?

**Comment by Jhobean** [comment]
About the tag override for infinite ammo I'll use it. It give option to gain illimited ammo without changing the itemdef item or using trigger. Exactly what I need to uptomize one of my script.

**Comment by GladieUO** [comment]
@HitReactive -> I love this trigger! Not sure if we could alter the amount of damage received from reaction before, but now we can surely😜

**Comment by canerksk** [comment]
Despite my ridiculous development process, I hope my changes are accepted. :sweat_smile:

**Pull request closed without merging**
