### PR TITLE
Fix for issue #496: Adding the Blade Spirits spell to a spellbook added the Clumsy spell.

### PR DESCRIPTION
**Pull request by drk84**
This also caused a corruption of the more1 value of the spellbooks, probably causing the disappearance of the rest of the spells?
They will have to replace players spellbooks i guess

### CODE REVIEW

**Comment by cbnolok** [comment]
Doesn't this cause another bug? It reverts that, suboptimal at this point, commit

https://github.com/Sphereserver/Source-X/commit/892048b5e39e1df94bdca90a59a3c9d92aeff6ee

**Comment by drk84** [comment]
I tried adding the 32nd and 64th spell (recall and summon water elemental) and i am not getting the bug, but but to be sure what if i replace the checks:
**if (i < 32u)** and  ** if (i <= 64u)**
with
**ifuint(spell) <= 32u)**and ** if (uint(spell) <= 64u)**
?

**Comment by cbnolok** [comment]
If that works 😁 i have no pc on this week so i can't help with testing

**Comment by drk84** [comment]
Ah true i can't just use the
` if (uint(spell) <= 32u) and if (uint(spell) <= 64u)` 
because spells from other spellbooks  have an higher index.

**Pull request merged**
