### PR TITLE
FIX: When hiding/invis item color was not change (issue #525)

### PR DESCRIPTION
**Pull request by Jhobean**
There was 2 bugs

- When we hide/invis [Spell or potion], the item on the paperdoll was not taking the grey HUE
- When we modify the color of invis in the ini setting, the anim character AND the paperdoll was not changing.

image

This is a Fix for the issue #525 and a fix for the paperdoll

### CODE REVIEW

**Comment by cbnolok** [comment]
As far as i remember, on Sphere none of the paperdoll items were ever colored when invis/hidden, am i wrong? In that case, maybe an ini switch may be added to turn on the recoloring of the whole paperdoll, since it would be a feature change and not a fix, strictly speaking

**Comment by Jhobean** [comment]
What about The color of the skin?

**Comment by Jhobean** [comment]
Ok we must choose what we want about the paperdoll: 
1- Stay like now (only skin color change) (except insubtantial you have your paperdoll change too)

2- Like OSI (nothing change on paperdoll)
image

3- Like ServUo (All paperdoll change)

**Comment by cbnolok** [comment]
Historically sphere behaved like osi i think, without altering the skin on
the paperdoll.
I'd only add a switch to enable paperdoll coloring with the color of the
colorinvis being used

Il mar 1 dic 2020, 03:04 Jhobean <notifications@github.com> ha scritto:

**Comment by Jhobean** [comment]
Ok after verification, 55i and OSI is the same.
There is no modification on the paperdoll at all. I'll Try to make it work like this

**Comment by Jhobean** [comment]
With the last commit, I setted back the old 55i  and OSI like situation.

- When you hide, invis yourself, your skin color do not change on the paperdoll (Since 56d, your skin color was changing)

About the feature where you can set different color, for hidding or invis in the ini:
- Your paperdoll color AND your anim take the color you set.
It's an obligation because the Grey color on the anim is done by the client and not the server. If you want override this grey color, you must manually set the skin and item color (affect paperdoll as well)

- For doing it work, we must send a Full packet when we get hide and when we use invis spell. Avoid send a full packet was doing the cloth color did not change.

**Pull request merged**
