### PR TITLE
Editable DispID for chars 

### PR DESCRIPTION
**Pull request by DavideRei**
Editable DispID for chars to change char graphic/body without changing baseid/defname, like it was in 0.56c

### CODE REVIEW

**Comment by Jhobean** [comment]
I tested it. Work Great. Cool feature

**Comment by Raylde** [comment]
LGTM

**Comment by cbnolok** [comment]
There's a problem with that. You are changing the CHARDEF (CCharBase) dispid, not the dispid of a specific instance of that char (CChar).
I'd do the following: create a CChar::m_dwDispID member and a CChar::SetDispID method to set that. If a valid dispid wasn't set (0 or CREID_INVALID), get the chardef one with Char_GetDef() and return that

**Comment by Jhobean** [comment]
> There's a problem with that. You are changing the CHARDEF (CCharBase) dispid, not the dispid of a specific instance of that char (CChar). I'd do the following: create a CChar::m_dwDispID member and a CChar::SetDispID method to set that. If a valid dispid wasn't set (0 or CREID_INVALID), get the chardef one with Char_GetDef() and return that

Are you saying if I change a specific zombie to c_bird, all zombie will look like bird?

**Comment by cbnolok** [comment]
From the code, it looks so

**Comment by DavideRei** [comment]
lol it's true, just tried.

**Comment by DavideRei** [comment]
Fixed

**Comment by DavideRei** [comment]
it seems that if i set dispid on a npc with a spawn, the dispid remain attached to the spawn. Even if the npc dies, the modified graphic remain on the new spawned npc. The new dispid seems to remain saved somewhere.
How is that possible? @cbnolok

**Comment by Jhobean** [comment]
Need to do a manual .update to see modification. possible to force it in the server?

**Comment by Jhobean** [comment]
I'm not able reproduce the spawn point bug you mentionned. Seem ok on my side

**Comment by DavideRei** [comment]
yes, seems fine now

**Review by Jhobean — APPROVED** [review]

**Pull request merged**
