### PR TITLE
Block spelleffect on ridden chars and other fixes

### PR DESCRIPTION
**Pull request by DavideRei**
If you place multiple fire field spell on the ground, go over it while riding an horse and .serv.save @spelleffect is triggered on the horse. To solve this problem i blocked spelleffect and gethit blocked on ridden chars. Don't know why during saves ridden chars could be affected but i think that while ridden they shouldn't be get hitted by spell or damage.
Fix duration of hallucination spell.
Fix wrong layer for potion delay

### CODE REVIEW

**Comment by Tolokio** [comment]
The mount fix should be done by script while we find whats going on.
In my case I need to be able to damage mounts.

**Comment by DavideRei** [comment]
The problem is that the offline mount is teleported on the p of the owner when you save.
I don't understand why an offline mount should take damage, especially from magic fields.
@Tolokio can i ask why do you need mount damage? for DOT?

**Comment by Jhobean** [comment]
ON 55i mounted mount was teleported to 1,1 Now on X, mount follow you but on save I think they are place directly on you that why save create this bug.

**Comment by Jhobean** [comment]
> The mount fix should be done by script while we find whats going on. In my case I need to be able to damage mounts.

Do you have a script fix to propose? We could add it to script pack.
We could add it on e_horses

**Comment by DavideRei** [comment]
We could block spelleffect on ridden char if the spell has spellflag_field or spellflag_area

**Comment by Jhobean** [comment]
> We could block spelleffect on ridden char if the spell has spellflag_field or spellflag_area

This option seem interesting. That mean if pet is poisoned, it will take damage.

**Comment by xwerswoodx** [comment]
Honestly I am not sure about blocking every hit while Horse is riding, because if it's poisoned, it has to get damage from the poison until die or poison removed, but I agree about field, we may found better solutions for it because I think any ticking damage like poison shouldn't be blocked when player ride the mount.

**Comment by DavideRei** [comment]
I removed the block on getHit for ridden chars and blocked the spelleffect on ridden chars only for spells with SPELLFLAG_FIELD or SPELLFLAG_AREA.
Also i changed NpcActFollow to take the fight target only if the npc is in combat, maybe is related to #1215

I don't why github put in the pull request old commits

**Comment by Jhobean** [comment]
I think you roolback some PR 🤣  you should merge master ti your branch or redo your PR from a clean branch

**Pull request closed without merging**
