### PR TITLE
DIALOG INPUT

### PR DESCRIPTION
**Pull request by criminalx**
Implemented a new dialog section "input" - Provides input processing before button triggers. This section can be utilized to check if the input is valid (obj in range, line of sight, etc..). This should reduce amount of code in each button trigger.

### CODE REVIEW

**Comment by criminalx** [comment]
Added example in changelog

**Comment by Jhobean** [comment]
Nice feature!

**Comment by cbnolok** [comment]
I'd change the INPUT keyword to something more "meaningful" like PREBUTTON or something like that. Any thoughts?

**Comment by criminalx** [comment]
Perfect boss

**Pull request merged**
