### PR TITLE
Project clean up

### PR DESCRIPTION
**Pull request by Raylde**
Move and removed unused files and project folders changes

Result:
image

This required that PR #920 are merged

### CODE REVIEW

**Comment by cbnolok** [comment]
The idea is good, though that's knowledge i don't think wise to lose. I'd move first those files to an "archive" repo in the sphere organization

**Comment by Jhobean** [comment]
> The idea is good, though that's knowledge i don't think wise to lose. I'd move first those files to an "archive" repo in the sphere organization

Good idea. We move old there? https://github.com/Sphereserver/Source-Archive ?

**Comment by Jhobean** [comment]
Be aware, right now PR #920 is include in this PR (probably a mistake)
image

**Comment by Raylde** [comment]
> Be aware, right now PR #920 is include in this PR (probably a mistake) image

You are right.
I'm going to fix it

**Review by Raylde — COMMENTED** [review]
check changes

**Comment by Jhobean** [comment]
I made a PR on Archive where all DOC/Tool are move: https://github.com/Sphereserver/Source-Archive/pull/2

**Comment by cbnolok** [comment]
What does the build action do?

**Comment by Jhobean** [comment]
@cbnolok 
1- Every PR will have his artifact on the PR. With this, it will be possible to test someone PR without have to compile it.

2- Every merged Commit will generate a new Nightly build (will erase and replace the old one). This build will be available only in the release TAB of the github.

**Comment by cbnolok** [comment]
So, this will make appveyor useless? 

Il giorno 24 ott 2022, 18:52, alle ore 18:52, Jhobean ***@***.***> ha scritto:
***@***.***

**Comment by Raylde** [comment]
> So, this will make appveyor useless? Il giorno 24 ott 2022, 18:52, alle ore 18:52, Jhobean ***@***.***> ha scritto: ***@***.***
> […](#)
> 1- Every PR will have his artifact on the PR. With this, it will be possible to test someone PR without have to compile it. 2- Every merged Commit will generate a new Nightly build (will erase and replace the old one). This build will be available only in the release TAB of the github. -- Reply to this email directly or view it on GitHub: [#925 (comment)](https://github.com/Sphereserver/Source-X/pull/925#issuecomment-1289318456) You are receiving this because you were mentioned. Message ID: ***@***.***>

yes and now, both can continue to coexist buy i prefer move all workflows to github actions. Is better for all community can contribute, have more features and we can centralize everything else in github

**Comment by Jhobean** [comment]
Eventually we could probably push on the FTP with the workflow too. For now we should just keep both in parallel and testing it.

**Pull request merged**
