### PR TITLE
Fixed: Hits,Stam,mana can go in negative (Issue #406). Stacked Deed only consume 1

### PR DESCRIPTION
**Pull request by Jhobean**
Since the Stat_SetVal was an unsigned, negative value was impossible so -10 = 65550. It was impossible to make a check if value was negative.

Because the ival is now signed we can check if it's negative and ajust it to 0.

Because Ushort was able to go to (0, 65000). If we don't want change the functionnality, we must now use int (-65000, 65000)

Fix for issue #406

### CODE REVIEW

**Comment by Jhobean** [comment]
I know @xwerswoodx was saying it's better to keep ushort because we don't go in negative. In an other hand if you set a negative value on hits, it's evident you should die.  By doing the restriction in the server, some old script will be compatible.  

For example on our shard we added custom damage by doing src.hits -= 10 . All the fix are done in my script but we have the problem to on some custom item droping the hits. So player was using the item to drop below 0 and heal them full heal...

**Comment by cbnolok** [comment]
I prefer to keep that ushort for a lot of reasons (one of them: memory usage), also you should ideally do the check in scripts. If we really want to set negative values to kill chars, and we should talk about this, we can just do a check when setting the HITS keyword

**Comment by Jhobean** [comment]
"When setting the hitpoints" its in core or in script?

**Comment by Jhobean** [comment]
I try to track where the stat are calculated before the function set_val for making the check there. This calcul seem to be in parsing function and did not find it.

**Comment by cbnolok** [comment]
Search _HITS:, you can do a pre-check before assigning the value. If the int value is < 0, set that to 0. You can also use std::min for that

**Comment by Jhobean** [comment]
I changed the method. What do you think?
If number is negative, I force to 0

**Comment by Jhobean** [comment]
I added a little fix about t_deed. On my custom shard, t_deed can be stack. But when we use it, all the stack is consume.

**Pull request merged**
