### PR TITLE
Added missing features for Issue #241:

### PR DESCRIPTION
**Pull request by drk84**
New ini flag NPCCanFizzle, when enabled, a NPC can fizzle a spell when hit during combat.

TAG.NPCNoCastTill behaviour, this tag will not allow a NPC to cast a spell if tag.NPCNoCastTill > SERV.Time.

### CODE REVIEW

**Comment by cbnolok** [comment]
NPCCanFizzle is meant to work only for NPCs hitting other NPCs, right? Because it seems to not affect players hitting NPCs now. Also, i'd use a more descriptive name, because like that it seems that npcs don't fizzle in any case if this flag is off

**Comment by drk84** [comment]
It should works when a player hits an NPC in combat and the NPC is trying to cast something, i tested it with a NPC casting a slow spell like flamestrike and it seemed to work if i remember well..

I can change the name to NPCCanFizzleHit or NPCCanFizzleWhenHit btw or something similar

**Comment by cbnolok** [comment]
Then yes i'd change that to NPCCanFizzleHit or something similar but more specific if you prefer

**Comment by drk84** [comment]
I renamed it on NPCanFizzleOnHit

**Pull request merged**
