### PR TITLE
revert change of naword to nword to fix foundation issue

### PR DESCRIPTION
**Pull request by Raylde**
image

### CODE REVIEW

**Comment by Raylde** [comment]
Thanks to @JulianUO to found the bug, @cbnolok can u check if have any problem. This is a revert of the commit https://github.com/Sphereserver/Source-X/commit/a3416ab2bc5c7b1a4491d916d91f69b03202c760#diff-f7385a02d982b15bac26cc3345cd8ea4e80135f99067f5520007d0ebeb800107

**Comment by Raylde** [comment]
issue #1079

**Comment by AtillaG1** [comment]
Works for me.
However, while building in the builder menu, some of the items after clicking "Commit" change to different item.

**Comment by cbnolok** [comment]
Was this happening before the tainted commit?

**Comment by AtillaG1** [comment]
> Was this happening before the tainted commit?

just tested with Compiled at Apr  7 2023 (11:48:53) [build 3590 / GIT hash 744da2360303357a3f66ec71797a04fa90a113d0]
and its working fine here.

**Comment by cbnolok** [comment]
Okay so there's a last fix to be done here before merging

**Comment by AtillaG1** [comment]
Maybe the issue will be same just in sender?

**Pull request merged**
