### PR TITLE
Poisonfix

### PR DESCRIPTION
**Pull request by Tolokio**
Fix for poison bottles when u dclick on one.  
```
-FIXED: (Poison`s potions)
	-Now it dosnt raise magic resistance if poison comes from a potion.
	-Potion is consumed when dclick and the Empty bottle retrieved into backpack.
	-Eating animation added.
	-Poison str and duration fixed.
-Known Issues:
	-There is no cooldown for poison bottles.
         (Should a player who drink a poison wait for cooldown until he can drink a cure potion?
          or should a player be able to drink 1000 potion in one minute? Can`t have both unless we
	  add a specific cooldown just for poison potions. What does OSI?) 
```
	
This fix is done due this report of jhobean	

image

On a clean build, u need to activate this option on sphere.ini or poison will not take effect.

image

In OSI jhobean tested u get poisoned if u dclick on poison bottle.

### CODE REVIEW

**Comment by Jhobean** [comment]
I tested it and work well!  Good job

**Comment by Jhobean** [comment]
When merging this fix, we should merge this revert on X pack too
https://github.com/Sphereserver/Scripts-X/pull/35

**Comment by Tolokio** [comment]
I did a mistake. fixing it, dont merge

**Comment by Tolokio** [comment]
> I tested it and work well! Good job

Ty for testing :D I fixed one more mistake. Works fine for me now. Just left the Cooldown issue. What does OSI? Do they put cooldown to poison potions as well?

**Comment by drk84** [comment]
The code you added in CClientUse.cpp can be replace with.
`m_pChar->Use_Drink(pItem);`
and also you can remove 
`m_pChar->OnSpellEffect(SPELL_Poison, m_pChar, pItem->m_itSpell.m_spelllevel, nullptr);`
As it's already include in m_pChar->UseDrink

**Comment by drk84** [comment]
Even better, the case 
`if ( RES_GET_INDEX(pItem->m_itPotion.m_Type) == SPELL_Poison )`
can be removed as everything related to dclicking a potion (Except explosion potion) is handled by useDrink

**Pull request closed without merging**
