### PR TITLE
Fix char delete trigger appear for NPC

### PR DESCRIPTION
**Pull request by Jhobean**
Second fix for issue https://github.com/Sphereserver/Source-X/issues/1029

### CODE REVIEW

**Comment by Jhobean** [comment]
Ok, All work like expected except this:
When we delete a char with the client screen, f_onchar_delete is launch 2 times. The only way to avoid this is to create a second bool argument on char delete function.
image



image

**Comment by Tolokio** [comment]
Tested deeply and works fine. But I think:

-There is no need to set argo=char  as char is already in <src> and works fine in both cases (from login screen and ingame command)
-Leave argo as m_pclient (it dosnt work on any serv_trigger) or change it to be account if possible.

Found minor weird bug:
If u "remove 1" an online player and deny it by return 1 on f_onchar_delete, player will not be removed from game but from players screenshoot. SO player can't move until sphere resend his data back.

**Comment by Jhobean** [comment]
Seem complete like this.
I added WARNING RED message each time a character is deleted. When character is deleted via login screen, you have a little message and WARNING message just after.
image

**Comment by cbnolok** [comment]
That fixes also the bug reported above?

**Comment by Jhobean** [comment]
> That fixes also the bug reported above?

Not yet, ill check

**Comment by Jhobean** [comment]
BUg already fixed, ready to merge for me

**Pull request merged**
