### PR TITLE
@shoveCharacter request->#752

### PR DESCRIPTION
**Pull request by Tolokio**
Tested. No bugs found.

on=@personalspace2
Fires when a char is going to step another char. 
src->The char u step on
|->char steping on. 

-Why personalspace2 instead Shovecharacter?
Just cos this way it is listed one after another. For example at wiki or source's lists.

-Notes:
I realize this trigger fires a lot if u try to step on another character without having stam. Better to have light scripts there.

### CODE REVIEW

**Comment by Jhobean** [comment]
Don't hesitate to link the issue and the PR with the number #752 .
Good job

**Comment by drk84** [comment]
Missing revision changelog and i don't like the trigger name!

**Comment by Jhobean** [comment]
@personalspace_stepper? 😄

**Comment by drk84** [comment]
@Shove or @Bump

**Comment by Tolokio** [comment]
> @shove or @bump

I dont care name, i think it is grateful if it is listed next to @personalspace at wiki and source lists. Both do almost the same, shouldnt be far from each other. Maybe @Personalspace_shove

**Comment by drk84** [comment]
Eh no eh it's important the trigger name

**Comment by Jhobean** [comment]
The trigger appear on the person bumping the other player. Bump look good.
Aboit wiki, we will add note on personnalspace and link the new one.

**Comment by Tolokio** [comment]
well, U think both names should be similar but ok. then what name?

@shove? @bump?

**Comment by Jhobean** [comment]
Weird
Shipturn (old style is there again)
Screenshot_20221227_094625_Chrome

**Comment by Jhobean** [comment]
Could you add the detail in changelog too?

**Comment by drk84** [comment]
yes Missing revision file also name it  @CharShove it will perfectly in the wiki @immagine

**Comment by canerksk** [comment]
> yes Missing revision file also name it @CharShove it will perfectly in the wiki @immagine

what are you talking about revision file? I did not fully understand?

**Comment by drk84** [comment]
The changelog.txt file were we put all the changes / fixes etc.
immagine

**Comment by canerksk** [comment]
@drk84 I guess you're talking about writing the description of the changes we made in Changelog.txt?

**Comment by drk84** [comment]
yes

**Pull request merged**
