### PR TITLE
Z Correction Tests

### PR DESCRIPTION
**Pull request by xwerswoodx**

### CODE REVIEW

**Comment by Tolokio** [comment]
Tested with 7.0.97.25
-It is hard to find a spot where sphere gets different Z than UOClient. In thoose cases, diference is -1 or +1, much better than before.
-This fix many terrain issues where Uoclient allow u to climb a hill but sphere dosnt. It is almost impossible to find one of this cases now.
-I just find a case where heights get mess but I think it is very rare case. I upload a ScreenShot
image
At screenshoot u can see diference betwen sphere(blue) and uoclient(orange) heights.

The arrangement is not perfect but offers a substantially significant improvement

**Comment by xwerswoodx** [comment]
I push another build, it should be fixed for the location on the picture, I am still doing a check if it causes any other issue

**Comment by Tolokio** [comment]
Much better fix,  Xwerswoodx found two spots with +1 and -1. I wasnt able to find any. For me is enought accurate to be implemented. Thoose spots Xwerswoodx found are just very very rare cases and just +1 or -1. We should check if runuo or servuo have the same problem there just for curiosity.

**Comment by Tolokio** [comment]
I ended my method to fix height, I think it does not worth at least how I did it. I think it increase cpu and memory usage a lot.

**Comment by xwerswoodx** [comment]
Yeah a bit silly, I would like to do some more checks to make it more accurate but it uses so much cpu if I do it, so I think with this way it can be best to stop, I am not sure what else I can do anymore honestly.

**Comment by Jhobean** [comment]
(Issue: #983, #617, #877) (Issue: #779)(Issue: #1112) (Issue: #720)

**Pull request merged**
